#function
- groupby() = แบ่งข้อมูลเป็นกลุ่ม
    df.groupby("group_column")["value_column"]
- mean() = หาค่าเฉลี่ย
    groupby_result.mean() หรือ series.mean()
- agg() = สรุปหลายค่าในครั้งเดียว
    grouped.agg(["count", "mean","median" ])
- sort_values() = เรียงข้อมูล
    series.sort_values(ascending=False)

## OBERVABLE ```Properties``` , ```Function```, ```Method```
- ```Properties``` = don't include () ex ==> .shape, .columns
- ```Methods``` = calling with obj. and inculde () ==> df.query() , isin()
- ```Functions``` = include () ==> ```read_csv()```, ```plt.show()```, ```plt.title()``` etc.

In [4]:
import pandas as pd

In [9]:
df = pd.read_csv("../data/footballers.csv")
df.head
print(df.shape[0])

46

In [ ]:
# New groupby league and find ovr avg
leauge_ovr_mean = df.groupby("league")["overall"].mean()
leauge_ovr_mean

league
Bundesliga          87.250000
La Liga             74.818182
Ligue 1             86.000000
MLS                 90.000000
Premier League      80.368421
Saudi Pro League    86.000000
Serie A             86.857143
Name: overall, dtype: float64

In [7]:
filter_leauge = df["league"].isin(["MLS"])
filter_leauge

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
Name: league, dtype: bool

In [ ]:
#Sorted values
# ascending=False ... greater to lower
# ascending=True ... lower to greater
# .reset_index() = Not include type index and convert to DataFrame() 
sorted_league = leauge_ovr_mean.sort_values(ascending=False).reset_index()
sorted_league
# Define new name column = new name column
sorted_league.columns = ["League", "Average_overall"]

display(sorted_league.round(2))

             League  Average_overall
0               MLS            90.00
1        Bundesliga            87.25
2           Serie A            86.86
3  Saudi Pro League            86.00
4           Ligue 1            86.00
5    Premier League            80.37
6           La Liga            74.82

In [16]:
# .agg()
position_stats = df.groupby("position")["overall"].agg(["count","mean", "median"]).sort_values(by="mean", ascending=False)


position_stats.round(2)
#.agg(["count", "mean", "median"]).sort_values(by="mean", ascending=False)

# posittion_stats.round(2)

          count   mean  median
position
LB            2  92.50    92.5
LW            6  88.17    88.0
RW            4  88.00    87.5
ST            8  86.62    85.5
RB            2  83.00    83.0
CAM           6  80.50    80.0
CB            6  80.17    80.5
CM            6  79.83    83.5
CDM           3  79.67    79.0
GK            3  44.67    46.0