### Function
- `.reset_index()` = เปลี่ยนชื่อกลุ่มที่เป็น Index ให้กลับมาเป็นคอลัมน์ปกติในตาราง
  
- `.iloc[0]` = เลือกตำแหน่งแถวตามลำดับตัวเลข(0 คือแถวแรกสุด) ห้ามใส่วงเล็บ

- `f-string` = รูปแบบข้อความ Python ที่แทรกค่าตัวแปรลงในประโยคได้ เช่น f"{name} เฉลี่ย {val:.1f}

In [8]:
import pandas as pd

df = pd.read_csv("../data/footballers.csv")
display(df.head(3))

,name,club,league,nationality,position,age,height_cm,overall,pace,shooting,passing,dribbling,defending,physical,value_millions
0,Lionel Messi,Inter Miami,MLS,Argentina,RW,37.0,170.0,90,87,90,91,94,34,65,45
1,Cristiano Ronaldo,Al Nassr,Saudi Pro League,Portugal,ST,39.0,187.0,86,78,89,82,83,32,75,15
2,Kylian Mbappe,Real Madrid,La Liga,France,ST,26.0,178.0,91,97,88,80,92,36,78,180

In [9]:
league_report =(
    df.groupby("league")["overall"]
    .agg(player_count="count", avg_overall="mean")
    .round(2)
    .sort_values(by="avg_overall",ascending=False)
    .reset_index()
)

print("<== Table for Manager ==>")
display(league_report)

<== Table for Manager ==>

             league  player_count  avg_overall
0               MLS             1        90.00
1        Bundesliga             4        87.25
2           Serie A             7        86.86
3  Saudi Pro League             1        86.00
4           Ligue 1             3        86.00
5    Premier League            19        80.37
6           La Liga            11        74.82

In [19]:
top_league = league_report.iloc[0]
sample_size = len(df)

sentence1 = f"Info player league Top score {top_league['league']} league"
sentence2 = f"Score overall avg {top_league['avg_overall']} from player in this league {int(top_league['player_count'])} player"
sentence3 = f"Only {sample_size} player in 5 league"

full_story = f""""
1. {sentence1}
2. {sentence2}
3. {sentence3}
"""
print(full_story)

"
1. Info player league Top score MLS league
2. Score overall avg 90.0 from player in this league 1 player
3. Only 46 player in 5 league